### ISSUE TITLE
giscus 配置改一下谢谢喵

### ISSUE THREAD

**Issue by TonyCrane** [AnjaReese/AnjaReese.github.io#1]
https://github.com/AnjaReese/AnjaReese.github.io/blob/8d277b8e4b83c7dfa866e3ffe6b9406ab64f4fc8/overrides/partials/comments.html#L4-L18

这里去 https://giscus.app/ 生成，不然会把评论的 discussion 创建到我的 repo 里

**Comment by AnyaReese** [comment]
# 🧎
sry for the inconvenience, I fixed it now
